ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_max_auth_retries: 3
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2

os_auth_pw_max_age: 90
os_auth_pw_min_len: 12
os_env_umask: '027'
os_kernel_modules_blacklist: []
