- name: Eliminar contenedores previos
  shell: docker compose -f {{ compose_file }} down
  args:
    chdir: /home/ubuntu/app
  ignore_errors: yes

- name: Levantar contenedores del microservicio
  shell: docker compose -f {{ compose_file }} up -d --build
  args:
    chdir: /home/ubuntu/app
