---

- name: Instalar dependencias necesarias para Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    state: present
    update_cache: yes

- name: Crear directorio para keyrings de Docker
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

# Descargar y convertir la clave GPG de Docker en formato correcto
- name: Descargar y configurar clave GPG de Docker
  shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: A침adir repositorio Docker para Ubuntu
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Actualizar cache APT
  apt:
    update_cache: yes

- name: Instalar Docker y plugins
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Iniciar y habilitar Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: A침adir usuario ubuntu al grupo docker
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Crear carpeta /home/ubuntu/app
  file:
    path: /home/ubuntu/app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Verificar instalaci칩n Docker
  command: docker --version
  register: docker_version
  changed_when: false

- debug:
    msg: "Docker instalado: {{ docker_version.stdout }}"

- name: Verificar instalaci칩n Docker Compose
  command: docker compose version
  register: docker_compose_version
  changed_when: false

- debug:
    msg: "Compose instalado: {{ docker_compose_version.stdout }}"
