---

# Asegurar dependencias básicas
- name: Instalar paquetes necesarios
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

# Crear directorio para la clave
- name: Crear directorio para keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

# Descargar clave GPG oficial de Docker
- name: Descargar clave GPG de Docker
  shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

# Dar permisos a la clave
- name: Cambiar permisos de la clave GPG
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'

# Añadir repositorio oficial de Docker
- name: Añadir repositorio Docker
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable

# Actualizar repos
- name: Ejecutar apt update
  apt:
    update_cache: yes

# Instalar Docker Engine
- name: Instalar Docker Engine y plugins
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

# Iniciar y habilitar Docker
- name: Iniciar y habilitar Docker
  systemd:
    name: docker
    state: started
    enabled: yes

# Añadir usuario ubuntu al grupo docker
- name: Añadir ubuntu al grupo docker
  user:
    name: ubuntu
    groups: docker
    append: yes

# Crear carpeta app
- name: Crear carpeta para microservicios
  file:
    path: /home/ubuntu/app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

# Verificar Docker
- name: Verificar la instalación de Docker
  command: docker --version
  register: docker_version
  ignore_errors: yes

- debug:
    msg: "Docker instalado: {{ docker_version.stdout }}"

# Verificar Compose
- name: Verificar Docker Compose
  command: docker compose version
  register: docker_compose_version
  ignore_errors: yes

- debug:
    msg: "Compose instalado: {{ docker_compose_version.stdout }}"
  
- name: Instalar pip para Python 3
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Instalar virtualenv
  apt:
    name: python3-venv
    state: present

- name: Crear virtualenv para Ansible
  command: python3 -m venv /home/ubuntu/ansible-venv
  args:
    creates: /home/ubuntu/ansible-venv

- name: Instalar Docker SDK dentro del venv
  pip:
    name: docker
    virtualenv: /home/ubuntu/ansible-venv